### ISSUE TITLE
Several models from Cube/Cube 2 fail to import

### ISSUE THREAD

**Issue by Calinou** [lennart-g/blender-md2-importer#3]
**OS:** Fedora 31
**Blender version:** 2.83 (with Pillow installed)

[hudguns_old.zip](https://github.com/lennart-g/blender-md2-importer/files/5147139/hudguns_old.zip)

In the ZIP above, I can only import the MD2 models in the `rocket` and `chaing` folder (which import perfectly, with animations and textures included). None of the other MD2 models can be imported successfully. For instance, I get the following error message with `shotg/tris.md2`:

![image](https://user-images.githubusercontent.com/180032/91664838-ffed9680-eaf1-11ea-8e2a-d3fbe3b3e2b5.png)

**Comment by lennart-g** [comment]
Just gave it a try (and noticed that the script won't work on windows because it assumes paths to contain "/" instead of "\\").

One of the models ("/gl") is an md3 file - a different format that's not supposed to work.

For the other models the issue is that your models don't have a skin file stored inside. For those cases, check "Load custom skin:" and enter the skin path relative to the directory containing the md2 model.

The following is the header of one of those md2 files, num_skins=0 shows that no path is specified for that file:
`header md2_t(ident=844121161, version=8, skinwidth=256, skinheight=256, framesize=1252, num_skins=0, num_xyz=303, num_st=320, num_tris=335, num_glcmds=3351, num_frames=30, ofs_skins=68, ofs_st=68, ofs_tris=1348, ofs_frames=5368, ofs_glcmds=42928, ofs_end=56332)`

I know, a lot of error handling is still missing :)

From what I heard many games supporting md2 files ignore the stored path and instead pick the local "skin.something" as skin by default.
